spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/booking_base?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/booking_base?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver
#logging:
#  level:
#    org.springframework.web: "debug"
#    org.hibernate: "error"
#  file:
#    name: "log/myapplication.log"

jwtconfig:
  secret: secrets
  expiration: 120000

